### ISSUE TITLE
Article in progress roll over

### ISSUE THREAD

**Issue by vinyll** [productownerinTO/producTOwner#5]
When clicking on "more…" the _article in progress_ box appears.
When accidentaly rolling over the title the background color interact catching my attention.
However there seems to be no reason for that as the title is not clickable nor giving any further information on tap.

**Comment by fuentesloic** [comment]
Oh ... I know all the modal (interaction, design, content,...) is not working now because I just thought some stuff inside.

**Comment by vinyll** [comment]
I mean the title bar seems clickable (rolling over changes the bg color) but is not

**Comment by vinyll** [comment]
Why is this closed? 😿

**Comment by fuentesloic** [comment]
because I fix it
