### ISSUE TITLE
XHTML formatting uniformity

### ISSUE THREAD

**Issue by vinyll** [productownerinTO/producTOwner#6]
```
<link rel="stylesheet" href="main.css" />
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
```
The first is written XHTML style and the second is kwarks mode style.

**Comment by fuentesloic** [comment]
It's fixed ! I erased the last link into <script src="https://use.fontawesome.com/ebcf2035af.js"></script>
