### ISSUE TITLE
nav > ul > li > article

### ISSUE THREAD

**Issue by vinyll** [productownerinTO/producTOwner#7]
The HTML structure has something unexpected in its structure:

```html
<nav>
        <ul>
          <!-- WEBDIVING -->
          <li>
            <a href="#webdiving">
              <img src="img/pf/webdiving.png" alt="WebDiving" />
            </a>
            <article id="webdiving" class="modaloverlay">
                …
```
The article is not the element of the navigation but the destination. It should therefore not be in the `nav`.

Maybe that using `nav` you may drop the `ul > li` too.

A suggestion would then be:

```html
<nav>
    <a href="#webdiving"><img src="img/pf/webdiving.png" alt="WebDiving" /></a>
    <a href="#scolia"><img src="img/pf/scolia.png" alt="Scolia" /></a>
    …
```
Also it would be so much cleared that the comments would become useless! ;)

**Comment by fuentesloic** [comment]
I totally agree with you but to build the modal (only with CSS) I need to hidden the article in the same part to activate it, isn't ?
Maybe I need to use JS to move the class ...

**Comment by vinyll** [comment]
I'm not talking about building the modal with CSS but having the `<nav>` not containing `<article>` nodes.
Maybe could you have the `<article>` after the `</nav>` end?

**Comment by fuentesloic** [comment]
It's a nonsense I get it ! 
Madre de dio ... me voila parti pour du JS maintenant ^^

**Comment by vinyll** [comment]
Mhh… I don't think that has anything to do with JS.
Just get your HTML clean:
```html
<nav>
  ...
</nav>

<article…
</article>
<article…
</article>
<article…
</article>
```

**Comment by fuentesloic** [comment]
Ok I see ... (really this time). 
But question : I don't need to put all the articles into a <ul> <li> ?

**Comment by vinyll** [comment]
No

**Comment by fuentesloic** [comment]
Ok so it's fixed (and that works !)
