### ISSUE TITLE
LinkedIn / email / github icons must be guessed

### ISSUE THREAD

**Issue by vinyll** [productownerinTO/producTOwner#8]
When rolling over one of those icons there's no title nor tooltip to indicate what is the subject or the action.
Therefore we must guess that clicking on the paper plane will send an email and we must know the linkedin and github or what they are for.
I'd suggest at least adding a title on each such as:
- view my resume
- contact me by email
- explore my source code

Applying this philosophy may be useful in other clickable images…

**Comment by fuentesloic** [comment]
Done !
